---

- name: Install pm2
  tags: pm2
  npm:
    name: pm2
    global: yes
    state: present


- name: Copy default html file for website(Ubuntu apache2)
  tags: copy-backend
  synchronize:
    src: index_site.html
    dest: /var/www/html/index.html
  notify: Restart apache2 server
  when: ansible_distribution == "Ubuntu"


- name: Copy default html file for website(OracleLinux Nginx)
  tags: copy-backend-nginx-oracle
  synchronize:
    src: index_site.html
    dest: /usr/share/nginx/html/index.html
  notify: Restart nginx server
  when: ansible_distribution == "OracleLinux"


