---

- hosts: all
  become: true
  roles:
    - base


- hosts: front_end_server
  become: true
  roles:
    - front_end_servers


- hosts: backend_server
  become: true
  roles:
    - backend_servers
