---

- hosts: all
  become: true
  roles:
    - base

- hosts: apache_server
  become: true
  roles:
    - apache_servers

- hosts: nginx_server
  become: true
  roles:
    - nginx_servers

- hosts: frontend_server
  become: true
  roles:
    - frontend_servers


- hosts: backend_server
  become: true
  roles:
    - backend_servers
