---

- hosts: all
  become: true
  tasks:


- hosts: front_end_server
  become: true
  tasks:

  - name: update repository index and install nginx
    tags: nginx
    apt:
      update_cache: yes
      name: nginx
      state: latest

  - name: Copy default html file for website
    tags: nginx,apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: 0644

  - name: Start nginx server
    tags: nginx
    service:
      enabled: yes
      name: nginx
      state: started

- hosts: backend_server
  become: true
  tasks:

  - name: update repository and install apache server
    tags: apache,apache2
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: Copy default html file for website
    tags: nginx,apache,apache2
    copy:
      src: index_site.html
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: 0644

  - name: start apache server
    tags: apache, apache2
    service:
      name: apache2
      state: started
      enabled: yes
