---

- hosts: all
  become: true
  tasks:

  - name: update repository index and install nginx
    apt:
      update_cache: yes
      name: nginx
      state: latest

  - name: Start nginx server
    service:
      enabled: yes
      name: nginx
      state: started
