---

- hosts: all
  become: true
  roles:
    - base


- hosts: front_end_server
  become: true
  roles:
    - front_end_servers


- hosts: apache_backend_server
  become: true
  roles:
    - apache_backend_servers
