---

- hosts: all
  become: true
  roles:
    - base


- hosts: frontend_server
  become: true
  roles:
    - front_end_servers


- hosts: backend_server
  become: true
  roles:
    - apache_backend_servers
