---

- name: Copy default html file for website(Ubuntu Nginx)
  tags: copy-frontend
  synchronize:
    src: default_site_nginx.html
    dest: /var/www/html/index.html
  notify: Restart nginx server
  when: ansible_distribution == "Ubuntu"


- name: Copy default html file for website(Ubuntu apache)
  tags: copy-frontend
  synchronize:
    src: default_site_apache.html
    dest: /var/www/html/index.html
  when: ansible_distribution == "Ubuntu"
  notify: Restart apache2 server


- name: Copy default html file for website(OracleLinux apache)
  tags: copy-frontend
  synchronize:
    src: default_site_apache.html
    dest: /var/www/html/index.html
  when: ansible_distribution == "OracleLinux"
  notify: Restart httpd server


- name: Install unzip
  package:
    name: unzip


- name: Copy picknpay zip file from github
  unarchive:
    src: https://github.com/Hardarmyyy/pick-n-pay-app/archive/refs/heads/main.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: hardarmyyy
    group: hardarmyyy
    mode: 0644


