---

- name: Restart nginx server
  service:
    name: nginx
    state: restarted

- name: Restart apache2 server
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: Restart httpd server
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: ansible_distribution == "OracleLinux"

