---

- name: Stop Nginx server(Ubuntu)
  tags: stop-nginx
  service:
    name: nginx
    state: stopped
  when: ansible_distribution == "Ubuntu"


- name: Uninstall Nginx server(Ubuntu)
  tags: uninstall-nginx
  apt:
    name: nginx
    state: absent
  when: ansible_distribution == "Ubuntu"


- name: Stop httpd server(OracleLinux)
  tags: stop-httpd
  service:
    name: httpd
    state: stopped
  when: ansible_distribution == "OracleLinux"


- name: Uninstall httpd server(OracleLinux)
  tags: uninstall-httpd
  dnf:
    name: httpd
    state: absent
  when: ansible_distribution == "OracleLinux"

