---

- name: Update system packages across all systems(Ubuntu)
  tags: updateSystem
  apt:
    update_cache: yes
  changed_when: false #This will enable the task to run under the hood without showing changes on the playbook tasks

- name: Download node package repository across all systems (Ubuntu)
  tags: node
  shell: |
    sudo curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

- name: Install nodejs and npm across all systems (Ubuntu)
  tags: nodejs,npm
  shell: |
    sudo apt-get install nodejs -y

- name: Copy the jenkins script file to the remote systems
  tags: jenkins-scripts
  copy:
    src: jenkins.sh
    dest: /home/hardarmyyy
    owner: hardarmyyy
    group: hardarmyyy
    mode: 0700

- name: Run the jenkins script file to install jenkins on remote systems
  tags: jenkins-scripts
  shell: |
    bash jenkins.sh


