---

- name: Install apache server(Ubuntu)
  tags: apache,apache2
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: Start apache server(Ubuntu)
  tags: apache,apache2
  service:
     name: apache2
     state: started
     enabled: yes
  when: ansible_distribution == "Ubuntu"


- name: Install apache server (OracleLinux)
  tags: apache,apache2,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "OracleLinux"


- name: Start apache server(OracleLinux)
  tags: apache,apache2,httpd
  service:
     name: httpd
     state: started
     enabled: yes
  when: ansible_distribution == "OracleLinux"


